"""Render + apply PostGIS table DDL from a ``SchemaPlan``.

This is one of only two PostgreSQL-specific modules (the other is
``functions.py``). Statement generation and application are kept separate so a
future migration emitter can reuse ``table_statements`` without executing it.

DDL is intentionally minimal/structural for now (column types, PK, geometry
type+SRID, GiST on geometry, FKs). Richer constraints (CHECK, code-list
enforcement, nullability on every attribute) are the deferred "validation in
the DB" concern.
"""
# ruff: noqa: S608 - This module generates SQL DDL from validated schema-plan
# identifiers and literal seed values derived from dataset descriptions.

from __future__ import annotations

import psycopg

from geocomponents.schema.plan import (
    CollectionPlan,
    ColumnPlan,
    SchemaPlan,
    TablePlan,
)

# PostgreSQL's NAMEDATALEN default. Identifiers longer than this are silently
# truncated by the server, so two distinct long names can collide.
_PG_MAX_IDENT_LEN = 63


def _quote_literal(value: str) -> str:
    return value.replace("'", "''")


def _column_ddl(col: ColumnPlan) -> str:
    parts = [f'"{col.name}"', col.sql_type]
    if col.auto_increment:
        parts.append("generated by default as identity")
    if col.primary_key:
        parts.append("primary key")
    if col.default is not None:
        parts.append(f"default {col.default}")
    if not col.nullable and not col.primary_key:
        parts.append("not null")
    return " ".join(parts)


def _table_ddl(table: TablePlan) -> str:
    lines = [_column_ddl(c) for c in table.columns]
    geom = table.geometry
    geometry_string = f'"{geom.name}" geometry({geom.postgis_type}, {geom.srid})'
    if not geom.nullable:
        geometry_string += " not null"
    lines.append(geometry_string)
    cols = ",\n  ".join(lines)
    return f"create table if not exists {table.qualified} (\n  {cols}\n)"


def _fk_constraint_name(table_name: str, column: str) -> str:
    """Return the ``<t>_<c>_fkey`` name if it fits PG's 63-char identifier
    limit; otherwise raise ``ValueError``.
    """
    name = f"{table_name}_{column}_fkey"
    if len(name) > _PG_MAX_IDENT_LEN:
        raise ValueError(
            f"FK constraint name {name!r} is {len(name)} chars, exceeds PG's "
            f"{_PG_MAX_IDENT_LEN}-char identifier limit. Shorten the "
            f"collection ({table_name!r}) or relationship (that yielded column "
            f"{column!r}) name."
        )
    return name


def _fk_ddl(table: TablePlan) -> list[str]:
    stmts: list[str] = []
    for fk in table.foreign_keys:
        cname = _fk_constraint_name(table.name, fk.column)
        stmts.append(
            f"alter table {table.qualified} "
            f'add constraint "{cname}" '
            f'foreign key ("{fk.column}") '
            f'references {fk.ref_table} ("{fk.ref_column}") '
            "on delete set null"
        )
    return stmts


def _extra_index_ddl(collection_name: str, table: TablePlan) -> list[str]:
    """Emit CREATE INDEX for each IndexPlan attached to a table."""
    stmts: list[str] = []
    for i, idx in enumerate(table.indexes):
        unique = "unique " if idx.unique else ""
        method = f" using {idx.method}" if idx.method != "btree" else ""
        name = f'"{collection_name}_{i}_idx"'
        stmts.append(
            f"create {unique}index if not exists {name} "
            f"on {table.qualified}{method} ({idx.expression})"
        )
    return stmts


def _geometry_index_ddl(plan: CollectionPlan) -> str:
    geom = plan.table.geometry.name
    return (
        f'create index if not exists "{plan.collection_name}_geometry_idx" '
        f'on {plan.table.qualified} using gist ("{geom}")'
    )


def _upsert_index_ddl(plan: CollectionPlan) -> str | None:
    # The outward identifier is now the row id; the primary key already indexes it.
    return None


def _change_trigger_function_ddl(plan: CollectionPlan) -> str:
    table = plan.table
    function_name = f"_{plan.collection_name}_record_change"
    dataset = _quote_literal(table.schema)
    collection = _quote_literal(plan.collection_name)
    identifier = table.id_column
    geometry = table.geometry.name
    srid = table.geometry.srid
    return f"""\
create or replace function {table.schema}.{function_name}()
returns trigger language plpgsql as $trigger$
begin
    if current_setting('geocomponents.suppress_change_events', true) = 'on' then
        return case when TG_OP = 'DELETE' then OLD else NEW end;
    end if;
    if TG_OP = 'INSERT' then
        perform geocomponents_event.record_change(
            '{dataset}', '{collection}', 'create', NEW."{identifier}",
            null, NEW."{geometry}", {srid});
        return NEW;
    elsif TG_OP = 'UPDATE' then
        perform geocomponents_event.record_change(
            '{dataset}', '{collection}', 'update', NEW."{identifier}",
            OLD."{geometry}", NEW."{geometry}", {srid});
        return NEW;
    end if;
    perform geocomponents_event.record_change(
        '{dataset}', '{collection}', 'delete', OLD."{identifier}",
        OLD."{geometry}", null, {srid});
    return OLD;
end;
$trigger$"""


def _change_trigger_ddl(plan: CollectionPlan) -> str:
    table = plan.table
    trigger_name = f"{plan.collection_name}_record_change"
    function_name = f"_{plan.collection_name}_record_change"
    return f"""\
create or replace trigger "{trigger_name}"
after insert or update or delete on {table.qualified}
for each row execute function {table.schema}.{function_name}()"""


def _collection_capability_table_ddl(plan: SchemaPlan) -> str:
    return (
        f"create table if not exists {plan.schema_name}.collection_capability ("
        "collection text primary key, feature_model text not null)"
    )


def _collection_capability_seed_ddl(plan: SchemaPlan) -> str:
    values = ", ".join(
        f"('{_quote_literal(coll.collection_name)}', '{_quote_literal(coll.feature_model)}')"
        for coll in plan.collections
    )
    return (
        f"insert into {plan.schema_name}.collection_capability "
        "(collection, feature_model) values "
        f"{values} on conflict (collection) do update set "
        "feature_model = excluded.feature_model"
    )


def _schema_comment_ddl(plan: SchemaPlan) -> str:
    comment = _quote_literal(
        "Generated from a dataset description. Call through ogc.feature_* / ogc.transaction. "
        "The _<collection>_<op> functions are internal and their names may change."
    )
    return f"comment on schema {plan.schema_name} is '{comment}'"


def _collection_capability_comment_ddl(plan: SchemaPlan) -> str:
    comment = _quote_literal(
        "Per-collection feature_model catalogue for this dataset. "
        "The ogc dispatch layer reads it to refuse direct writes to topology collections."
    )
    return f"comment on table {plan.schema_name}.collection_capability is '{comment}'"


def _association_role_table_ddl(plan: SchemaPlan) -> str:
    s = plan.schema_name
    return (
        f"create table if not exists {s}.association_role ("
        "source_collection text not null, "
        "property text not null, "
        "target_collection text not null, "
        "primary key (source_collection, property))"
    )


def _association_table_ddl(plan: SchemaPlan) -> str:
    s = plan.schema_name
    return (
        f"create table if not exists {s}.association ("
        "source_collection text not null, "
        "source_id uuid not null, "
        "property text not null, "
        "target_id uuid not null, "
        f"primary key (source_collection, source_id, property, target_id), "
        f"foreign key (source_collection, property) "
        f"references {s}.association_role (source_collection, property))"
    )


def _association_role_seed_ddl(plan: SchemaPlan) -> str:
    values = ", ".join(
        f"('{_quote_literal(r.source_collection)}', "
        f"'{_quote_literal(r.property)}', "
        f"'{_quote_literal(r.target_collection)}')"
        for r in plan.association_role_rows
    )
    return (
        f"insert into {plan.schema_name}.association_role "
        "(source_collection, property, target_collection) values "
        f"{values} on conflict (source_collection, property) do update set "
        "target_collection = excluded.target_collection"
    )


def _association_index_ddl(plan: SchemaPlan) -> str:
    s = plan.schema_name
    return (
        f'create index if not exists "association_target_id_idx" '
        f"on {s}.association (target_id)"
    )


def _guard_association_role_removal(conn: psycopg.Connection, plan: SchemaPlan) -> None:
    """Raise RuntimeError if removing a property would orphan association rows."""
    schema = plan.schema_name
    table_exists = conn.execute(
        "select 1 from information_schema.tables "
        "where table_schema = %s and table_name = 'association_role'",
        (schema,),
    ).fetchone()
    if not table_exists:
        return
    current = {
        (row[0], row[1])
        for row in conn.execute(
            f"select source_collection, property from {schema}.association_role"
        ).fetchall()
    }
    new_props = {(r.source_collection, r.property) for r in plan.association_role_rows}
    removed = current - new_props
    if not removed:
        return
    blocking: list[str] = []
    for source_collection, prop in sorted(removed):
        count = conn.execute(
            f"select count(*) from {schema}.association "
            "where source_collection = %s and property = %s",
            (source_collection, prop),
        ).fetchone()[0]
        if count > 0:
            blocking.append(f"  {source_collection}.{prop}: {count} row(s)")
    if blocking:
        raise RuntimeError(
            f"apply-schema: removing {len(blocking)} property(ies) from "
            f"{schema}.association_role would orphan association rows:\n"
            + "\n".join(blocking)
        )


def table_statements(plan: SchemaPlan) -> list[str]:
    """One complete SQL command per list element (idempotent where possible).

    FK constraints come after all tables so collection order and cross-collection
    cycles don't matter.
    """

    stmts: list[str] = [
        "create extension if not exists postgis",
        # gen_random_uuid() (id column default) is core in PG >= 13 but requires
        # pgcrypto on PG <= 12. Cheap portability; no-op on modern servers.
        "create extension if not exists pgcrypto",
        f"create schema if not exists {plan.schema_name}",
        _schema_comment_ddl(plan),
        _collection_capability_table_ddl(plan),
        _collection_capability_comment_ddl(plan),
    ]
    if plan.association_role_rows:
        stmts.append(_association_role_table_ddl(plan))
        stmts.append(_association_table_ddl(plan))
    for coll in plan.collections:
        stmts.append(_table_ddl(coll.table))
    stmts.append(_collection_capability_seed_ddl(plan))
    if plan.association_role_rows:
        stmts.append(_association_role_seed_ddl(plan))
        stmts.append(_association_index_ddl(plan))
    for coll in plan.collections:
        stmts.append(_geometry_index_ddl(coll))
        stmts.extend(_extra_index_ddl(coll.collection_name, coll.table))
        if upsert_index := _upsert_index_ddl(coll):
            stmts.append(upsert_index)
        stmts.append(_change_trigger_function_ddl(coll))
        stmts.append(_change_trigger_ddl(coll))
    for coll in plan.collections:
        stmts.extend(_fk_ddl(coll.table))
    return stmts


def render_tables(plan: SchemaPlan) -> str:
    """Human-readable DDL script (for inspection / future migrations)."""
    return ";\n\n".join(table_statements(plan)) + ";\n"


def apply_tables(conn: psycopg.Connection, plan: SchemaPlan) -> None:
    """Create the PostgreSQL schema and tables declared by ``plan``, atomically.

    Per-statement savepoints let re-runs tolerate ``DuplicateObject`` (e.g. an
    FK that already exists) without discarding earlier statements in the same
    transaction.
    """
    with conn.transaction():
        _guard_association_role_removal(conn, plan)
        for stmt in table_statements(plan):
            try:
                with conn.transaction():
                    conn.execute(stmt)
            except psycopg.errors.DuplicateObject:
                # e.g. an FK constraint that already exists on re-application.
                continue
