-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE SCHEMA IF NOT EXISTS fkb_ar5;

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursarealtype
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default"
);

TRUNCATE fkb_ar5.arealressursarealtype RESTART IDENTITY;

INSERT INTO fkb_ar5.arealressursarealtype (identifier, description)
VALUES
    ('11', 'Bebygd'),
    ('12', 'Samferdsel'),
    ('21', 'Fulldyrka jord'),
    ('22', 'Overflatedyrka jord'),
    ('23', 'Innmarksbeite'),
    ('30', 'Skog'),
    ('50', 'Åpen fastmark'),
    ('60', 'Myr'),
    ('70', 'Snøisbre'),
    ('81', 'Ferskvann'),
    ('82', 'Hav'),
    ('99', 'Ikke kartlagt');

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursavgrensningstype
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default"
);

TRUNCATE fkb_ar5.arealressursavgrensningstype RESTART IDENTITY;

INSERT INTO fkb_ar5.arealressursavgrensningstype (identifier, description)
VALUES
    ('3000', 'Vanngrense'),
    ('3310', 'Isbregrense'),
    ('4206', 'Arealressursgrense'),
    ('7200', 'Samferdselgrense'),
    ('9111', 'Lagringsenhentsgrense'),
    ('9300', 'Ikke kartlagt grense');

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursflate
(
    objid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    objtype text COLLATE pg_catalog."default" DEFAULT 'ArealressursFlate'::text,
    lokalid text COLLATE pg_catalog."default" NOT NULL,
    identifikasjon_navnerom text COLLATE pg_catalog."default",
    identifikasjon_versjonid text COLLATE pg_catalog."default",
    oppdateringsdato timestamp without time zone NOT NULL,
    sluttdato timestamp without time zone,
    datafangstdato timestamp without time zone NOT NULL,
    registreringsversjon text COLLATE pg_catalog."default",
    informasjon text COLLATE pg_catalog."default",
    opphav text COLLATE pg_catalog."default" NOT NULL,
    omrade geometry(Polygon,25833),
    posisjon geometry(Point,25833),
    arealtype text COLLATE pg_catalog."default" NOT NULL,
    treslag text COLLATE pg_catalog."default" NOT NULL,
    skogbonitet text COLLATE pg_catalog."default" NOT NULL,
    grunnforhold text COLLATE pg_catalog."default" NOT NULL,
    klassifiseringsmetode text COLLATE pg_catalog."default" NOT NULL,
    verifiseringsdato timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursflate_avgrensesavarealressursgrense
(
    objid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    href text COLLATE pg_catalog."default",
    num text COLLATE pg_catalog."default",
    parentfk text COLLATE pg_catalog."default" NOT NULL,
    fk text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursflate_avgrensesavarealressursgrensefiktiv
(
    objid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    href text COLLATE pg_catalog."default",
    num text COLLATE pg_catalog."default",
    parentfk text COLLATE pg_catalog."default" NOT NULL,
    fk text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursgrense
(
    objid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    objtype text COLLATE pg_catalog."default" DEFAULT 'ArealressursGrense'::text,
    lokalid text COLLATE pg_catalog."default" NOT NULL,
    identifikasjon_navnerom text COLLATE pg_catalog."default",
    identifikasjon_versjonid text COLLATE pg_catalog."default",
    oppdateringsdato timestamp without time zone NOT NULL,
    sluttdato timestamp without time zone,
    datafangstdato timestamp without time zone NOT NULL,
    registreringsversjon text COLLATE pg_catalog."default",
    informasjon text COLLATE pg_catalog."default",
    opphav text COLLATE pg_catalog."default" NOT NULL,
    grense geometry(LineString,25833),
    avgrensingtype text COLLATE pg_catalog."default" NOT NULL,
    verifiseringsdato timestamp without time zone NOT NULL,
    kvalitet_datafangstmetode text COLLATE pg_catalog."default",
    kvalitet_noyaktighet integer,
    kvalitet_synbarhet text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursgrensefiktiv
(
    objid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    objtype text COLLATE pg_catalog."default" DEFAULT 'ArealressursGrenseFiktiv'::text,
    lokalid text COLLATE pg_catalog."default" NOT NULL,
    identifikasjon_navnerom text COLLATE pg_catalog."default",
    identifikasjon_versjonid text COLLATE pg_catalog."default",
    oppdateringsdato timestamp without time zone NOT NULL,
    sluttdato timestamp without time zone,
    datafangstdato timestamp without time zone NOT NULL,
    registreringsversjon text COLLATE pg_catalog."default",
    informasjon text COLLATE pg_catalog."default",
    opphav text COLLATE pg_catalog."default" NOT NULL,
    grense geometry(LineString,25833)
);

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursgrunnforhold
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default"
);

TRUNCATE fkb_ar5.arealressursgrunnforhold RESTART IDENTITY;

INSERT INTO fkb_ar5.arealressursgrunnforhold (identifier, description)
VALUES
    ('41', 'Blokkmark'),
    ('42', 'Fjell i dagen'),
    ('43', 'Grunnlendt'),
    ('44', 'Jorddekt'),
    ('45', 'Organisk jordlag'),
    ('46', 'Konstruert'),
    ('98', 'Ikke relevant'),
    ('99', 'Ikke registrert');

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressursskogbonitet
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default"
);

TRUNCATE fkb_ar5.arealressursskogbonitet RESTART IDENTITY;

INSERT INTO fkb_ar5.arealressursskogbonitet (identifier, description)
VALUES
    ('11', 'Impediment'),
    ('12', 'Lav'),
    ('13', 'Middels'),
    ('14', 'Høy'),
    ('15', 'Særs høy'),
    ('98', 'Ikke relevant'),
    ('99', 'Ikke registrert');

CREATE TABLE IF NOT EXISTS fkb_ar5.arealressurstreslag
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default"
);

TRUNCATE fkb_ar5.arealressurstreslag RESTART IDENTITY;

INSERT INTO fkb_ar5.arealressurstreslag (identifier, description)
VALUES
    ('31', 'Barskog'),
    ('32', 'Lauvskog'),
    ('33', 'Blandingsskog'),
    ('39', 'Ikke tresatt'),
    ('98', 'Ikke relevant'),
    ('99', 'Ikke registrert');

CREATE TABLE IF NOT EXISTS fkb_ar5.klassifiseringsmetode
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default"
);

TRUNCATE fkb_ar5.klassifiseringsmetode RESTART IDENTITY;

INSERT INTO fkb_ar5.klassifiseringsmetode (identifier, description)
VALUES
    ('sOrto', 'Ortofoto sikker'),
    ('uOrto', 'Ortofoto usikker'),
    ('sFelt', 'Felt sikker'),
    ('uFjern', 'Fjernmåling usikker'),
    ('uMeld', 'Melding fra grunneier - usikker'),
    ('uAnnen', 'Annen usikker');

CREATE TABLE IF NOT EXISTS fkb_ar5.opphav
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default"
);

TRUNCATE fkb_ar5.opphav RESTART IDENTITY;

INSERT INTO fkb_ar5.opphav (identifier, description)
VALUES
    ('nibio', 'NIBIO'),
    ('ok', 'NIBIO-ØK'),
    ('jm', 'NIBIO-JM'),
    ('skog', 'NIBIO-Skog'),
    ('komm', 'Kommune'),
    ('web', 'Kommune-Web'),
    ('vann', 'Vann'),
    ('samf', 'Samferdsel'),
    ('annet', 'Annet');

END;
