BEGIN;


CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS fkb_felles;

CREATE TABLE IF NOT EXISTS fkb_felles.registreringsversjon
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT registreringsversjon_pkey PRIMARY KEY (id)
);

TRUNCATE fkb_felles.registreringsversjon RESTART IDENTITY;



CREATE TABLE IF NOT EXISTS fkb_felles.datafangstmetode
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT datafangstmetode_pkey PRIMARY KEY (id)
);

TRUNCATE fkb_felles.datafangstmetode RESTART IDENTITY;

INSERT INTO fkb_felles.datafangstmetode (identifier, description)
VALUES
    ('byg', 'Som bygget'),
    ('ukj', 'Ukjent'),
    ('pla', 'Plandata'),
    ('sat', 'Satellittmålt'),
    ('gen', 'Generert'),
    ('fot', 'Fotogrammetri'),
    ('dig', 'Digitalisert'),
    ('lan', 'Landmålt');

CREATE TABLE IF NOT EXISTS fkb_felles.synbarhet
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT synbarhet_pkey PRIMARY KEY (id)
);

TRUNCATE fkb_felles.synbarhet RESTART IDENTITY;

INSERT INTO fkb_felles.synbarhet (identifier, description)
VALUES
    ('2', 'Middels synlig'),
    ('3', 'Ikke synlig'),
    ('0', 'Fullt ut synlig'),
    ('1', 'Dårlig gjenfinnbar i terreng');

END;
