-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE SCHEMA IF NOT EXISTS fkb_bane;

CREATE TABLE IF NOT EXISTS fkb_bane.hoydereferanse
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT hoydereferanse_pkey PRIMARY KEY (id)
);

TRUNCATE fkb_bane.hoydereferanse RESTART IDENTITY;

INSERT INTO fkb_bane.hoydereferanse (identifier, description)
VALUES
    ('fot', 'Fot'),
    ('ukjent', 'Ukjent'),
    ('topp', 'Topp');

CREATE TABLE IF NOT EXISTS fkb_bane.jernbaneplattformkant
(
    objid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    objtype text COLLATE pg_catalog."default" DEFAULT 'Jernbaneplattformkant'::text,
    lokalid text COLLATE pg_catalog."default" NOT NULL,
    identifikasjon_navnerom text COLLATE pg_catalog."default",
    identifikasjon_versjonid text COLLATE pg_catalog."default",
    oppdateringsdato timestamp without time zone NOT NULL,
    sluttdato timestamp without time zone,
    datafangstdato timestamp without time zone NOT NULL,
    verifiseringsdato timestamp without time zone,
    registreringsversjon text COLLATE pg_catalog."default",
    informasjon text COLLATE pg_catalog."default",
    kvalitet_datafangstmetode text COLLATE pg_catalog."default",
    kvalitet_noyaktighet integer,
    kvalitet_synbarhet text COLLATE pg_catalog."default",
    kvalitet_datafangstmetodehoyde text COLLATE pg_catalog."default",
    kvalitet_noyaktighethoyde integer,
    grense geometry(LineStringZ,5973),
    medium text COLLATE pg_catalog."default" NOT NULL,
    eksternpeker text COLLATE pg_catalog."default",
    CONSTRAINT jernbaneplattformkant_pkey PRIMARY KEY (objid),
    CONSTRAINT jernbaneplattformkant_lokalid_key UNIQUE (lokalid)
);

CREATE TABLE IF NOT EXISTS fkb_bane.jernbanetype
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT jernbanetype_pkey PRIMARY KEY (id)
);

TRUNCATE fkb_bane.jernbanetype RESTART IDENTITY;

INSERT INTO fkb_bane.jernbanetype (identifier, description)
VALUES
    ('S', 'Sporveg'),
    ('K', 'Kabelbane'),
    ('F', 'Forstadsbane'),
    ('J', 'Jernbane'),
    ('T', 'Tunnelbane');

CREATE TABLE IF NOT EXISTS fkb_bane.medium
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT medium_pkey PRIMARY KEY (id)
);

TRUNCATE fkb_bane.medium RESTART IDENTITY;

-- Inkonsekvent bruk av store og små bokstaver kommer fra FKB-definisjonen
INSERT INTO fkb_bane.medium (identifier, description)
VALUES
    ('T', 'På terrenget'),
    ('X', 'Ukjent'),
    ('D', 'Delvis under vann'),
    ('I', 'På Isbre'),
    ('U', 'Under terrenget'),
    ('V', 'I vann'),
    ('B', 'I Bygning'),
    ('L', 'I luft');    

CREATE TABLE IF NOT EXISTS fkb_bane.spormidt
(
    objid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    objtype text COLLATE pg_catalog."default" DEFAULT 'Spormidt'::text,
    lokalid text COLLATE pg_catalog."default" NOT NULL,
    identifikasjon_navnerom text COLLATE pg_catalog."default",
    identifikasjon_versjonid text COLLATE pg_catalog."default",
    oppdateringsdato timestamp without time zone NOT NULL,
    sluttdato timestamp without time zone,
    datafangstdato timestamp without time zone NOT NULL,
    verifiseringsdato timestamp without time zone,
    registreringsversjon text COLLATE pg_catalog."default",
    informasjon text COLLATE pg_catalog."default",
    kvalitet_datafangstmetode text COLLATE pg_catalog."default",
    kvalitet_noyaktighet integer,
    kvalitet_synbarhet text COLLATE pg_catalog."default",
    kvalitet_datafangstmetodehoyde text COLLATE pg_catalog."default",
    kvalitet_noyaktighethoyde integer,
    senterlinje geometry(LineStringZ,5973),
    jernbanetype text COLLATE pg_catalog."default" NOT NULL,
    hoydereferanse text COLLATE pg_catalog."default" NOT NULL,
    medium text COLLATE pg_catalog."default" NOT NULL,
    eksternpeker text COLLATE pg_catalog."default",
    CONSTRAINT spormidt_pkey PRIMARY KEY (objid),
    CONSTRAINT spormidt_lokalid_key UNIQUE (lokalid)
);

END;
