from pathlib import Path

import pytest

from geocomponents.descriptions.loader import load_resolved_datasets
from geocomponents.descriptions.models import (
    ResolvedCollection,
    ResolvedDataset,
    ResolvedField,
)
from geocomponents.schema import postgis
from geocomponents.schema.build import build_schema_plan
from geocomponents.schema.plan import OPERATIONS, READ_OPS

DESCRIPTIONS = Path(__file__).resolve().parents[1] / "descriptions"
WGS84_SRID = 4326


def _make_dataset(
    *,
    fields: list[ResolvedField] | None = None,
    server_managed_paths: dict[str, str] | None = None,
    outward_identifier_path: str | None = None,
) -> ResolvedDataset:
    """Minimal dataset fixture for build tests."""
    return ResolvedDataset(
        name="x",
        title="X",
        description="",
        collections=(
            ResolvedCollection(
                name="c",
                title="C",
                description="",
                feature_model="simple",
                geometry_type="Point",
                srid=4258,
                fields=tuple(fields or []),
                relationships=(),
                server_managed_paths=server_managed_paths or {},
                outward_identifier_path=outward_identifier_path,
            ),
        ),
    )


def _cadastre_plan():
    cad = next(d for d in load_resolved_datasets(DESCRIPTIONS) if d.name == "cadastre")
    return build_schema_plan(cad)


def _bane_plan():
    bane = next(d for d in load_resolved_datasets(DESCRIPTIONS) if d.name == "bane")
    return build_schema_plan(bane)


def _bygning_plan():
    bygning = next(
        d for d in load_resolved_datasets(DESCRIPTIONS) if d.name == "bygning"
    )
    return build_schema_plan(bygning)


def test_dataset_maps_to_schema_and_collections_to_tables():
    plan = _cadastre_plan()
    assert plan.schema_name == "cadastre"
    assert {c.collection_name for c in plan.collections} == {
        "parcels",
        "buildings",
        "blocks",
    }
    for coll in plan.collections:
        assert coll.table.qualified == f"cadastre.{coll.collection_name}"


def test_topology_collection_gets_a_table_but_only_read_ops():
    plan = _cadastre_plan()
    blocks = next(c for c in plan.collections if c.collection_name == "blocks")
    # It still has a table (reads need one), but no write functions.
    assert blocks.table.qualified == "cadastre.blocks"
    assert set(blocks.functions) == set(READ_OPS)


def test_standard_columns_and_geometry_present():
    plan = _cadastre_plan()
    parcels = next(c for c in plan.collections if c.collection_name == "parcels")
    names = {col.name for col in parcels.table.columns}
    assert {"id", "created_at", "updated_at"} <= names
    assert parcels.table.id_column == "id"
    assert parcels.table.geometry.geometry_type == "MultiPolygon"
    assert parcels.table.geometry.srid == WGS84_SRID


def test_relationship_becomes_fk_column():
    plan = _cadastre_plan()
    buildings = next(c for c in plan.collections if c.collection_name == "buildings")
    assert "parcel_id" in {col.name for col in buildings.table.columns}
    fks = {(fk.column, fk.ref_table) for fk in buildings.table.foreign_keys}
    assert ("parcel_id", "cadastre.parcels") in fks


def test_relationship_fk_ddl_is_rendered_with_stable_constraint_name():
    ddl = "\n".join(postgis.table_statements(_cadastre_plan()))
    assert "alter table cadastre.buildings" in ddl
    assert 'add constraint "buildings_parcel_id_fkey"' in ddl


def test_internal_function_names_are_private_and_per_operation():
    plan = _cadastre_plan()
    parcels = next(c for c in plan.collections if c.collection_name == "parcels")
    assert set(parcels.functions) == set(OPERATIONS)
    # Internal (private) names live in the dataset schema, prefixed with '_'.
    assert parcels.functions["items"] == "cadastre._parcels_items"


def test_pgcrypto_extension_declared_for_gen_random_uuid():
    """PG <= 12 lacks ``gen_random_uuid()`` in core; declaring pgcrypto keeps
    the id column default portable across PG versions."""
    stmts = postgis.table_statements(_cadastre_plan())
    assert any("create extension if not exists pgcrypto" in s for s in stmts)


def test_auto_increment_field_uses_postgresql_identity():
    plan = _bane_plan()
    platform = next(
        c for c in plan.collections if c.collection_name == "jernbaneplattformkant"
    )
    objid = next(c for c in platform.table.columns if c.name == "objid")
    assert objid.auto_increment
    ddl = "\n".join(postgis.table_statements(plan))
    assert '"objid" integer generated by default as identity not null' in ddl


def test_bane_business_key_gets_unique_nulls_not_distinct_index():
    ddl = "\n".join(postgis.table_statements(_bane_plan()))
    assert (
        'on bane.jernbaneplattformkant ("lokalid", "identifikasjon_navnerom") '
        "nulls not distinct"
    ) in ddl


def test_every_collection_gets_a_gist_index_on_geometry():
    plan = _cadastre_plan()
    stmts = postgis.table_statements(plan)
    for coll in plan.collections:
        expected = (
            f'create index if not exists "{coll.collection_name}_geometry_idx" '
            f'on {coll.table.qualified} using gist ("geometry")'
        )
        assert expected in stmts


def test_bane_geometry_columns_include_height():
    plan = _bane_plan()
    for collection_name in ("jernbaneplattformkant", "spormidt"):
        coll = next(c for c in plan.collections if c.collection_name == collection_name)
        assert coll.table.geometry.has_z
        assert coll.table.geometry.postgis_type == "MultiLineStringZ"
    ddl = "\n".join(postgis.table_statements(plan))
    assert '"geometry" geometry(MultiLineStringZ, 5973)' in ddl


def test_bygning_geometry_and_business_key_are_built_correctly():
    plan = _bygning_plan()
    coll = next(c for c in plan.collections if c.collection_name == "bygning")
    assert coll.table.geometry.has_z
    assert coll.table.geometry.postgis_type == "MultiLineStringZ"
    ddl = "\n".join(postgis.table_statements(plan))
    assert '"geometry" geometry(MultiLineStringZ, 5972)' in ddl
    assert (
        'on bygning.bygning ("lokalid", "identifikasjon_navnerom") nulls not distinct'
    ) in ddl


def test_bygning_omrade_geometry_and_business_key_are_built_correctly():
    plan = _bygning_plan()
    coll = next(c for c in plan.collections if c.collection_name == "bygning_omrade")
    assert coll.table.geometry.has_z
    assert coll.table.geometry.postgis_type == "MultiPolygonZ"
    ddl = "\n".join(postgis.table_statements(plan))
    assert '"geometry" geometry(MultiPolygonZ, 5972)' in ddl
    assert (
        'on bygning.bygning_omrade ("lokalid", "identifikasjon_navnerom") '
        "nulls not distinct"
    ) in ddl


def test_bygning_senterlinje_geometry_and_business_key_are_built_correctly():
    plan = _bygning_plan()
    coll = next(
        c for c in plan.collections if c.collection_name == "bygning_senterlinje"
    )
    assert coll.table.geometry.has_z
    assert coll.table.geometry.postgis_type == "MultiLineStringZ"
    ddl = "\n".join(postgis.table_statements(plan))
    assert '"geometry" geometry(MultiLineStringZ, 5972)' in ddl
    assert (
        'on bygning.bygning_senterlinje ("lokalid", "identifikasjon_navnerom") '
        "nulls not distinct"
    ) in ddl


def test_bygning_posisjon_geometry_and_business_key_are_built_correctly():
    plan = _bygning_plan()
    coll = next(c for c in plan.collections if c.collection_name == "bygning_posisjon")
    assert coll.table.geometry.has_z
    assert coll.table.geometry.postgis_type == "PointZ"
    ddl = "\n".join(postgis.table_statements(plan))
    assert '"geometry" geometry(PointZ, 5972)' in ddl
    assert (
        'on bygning.bygning_posisjon ("lokalid", "identifikasjon_navnerom") '
        "nulls not distinct"
    ) in ddl


# --------------------------------------------------------------------------
# FK constraint names must fit PG's 63-char NAMEDATALEN
# --------------------------------------------------------------------------
def test_fk_constraint_name_natural_when_short():
    """Common case: the human-readable ``<t>_<c>_fkey`` form is used verbatim
    so existing databases keep recognizing pre-applied constraints."""
    assert (
        postgis._fk_constraint_name("buildings", "parcel_id")
        == "buildings_parcel_id_fkey"
    )


def test_fk_constraint_name_raises_when_over_63():
    """Worst-case SafeIdentifier lengths (40 + 43) produce an 89-char natural
    name that PG would silently truncate to 63, risking collisions across
    distinct FKs. Fail loudly with an actionable message so the author shortens
    the source names rather than getting an opaque server-side collision."""
    long_table = "t" * 40
    long_column = "c" * 40 + "_id"  # 43 chars
    with pytest.raises(ValueError, match=r"63"):
        postgis._fk_constraint_name(long_table, long_column)


# --------------------------------------------------------------------------
# JSONB column injection metadata (Commit 3)
# --------------------------------------------------------------------------


def test_jsonb_field_with_server_managed_outward_identifier_sets_id_inject_key():
    """server_managed outward_identifier → ColumnPlan.id_inject_key populated."""
    ds = _make_dataset(
        fields=[
            ResolvedField(
                "identifikasjon",
                "jsonb",
                sub_fields=(
                    ResolvedField("lokalid", "text"),
                    ResolvedField("navnerom", "text"),
                ),
            )
        ],
        server_managed_paths={"identifikasjon.lokalid": "outward_identifier"},
    )
    plan = build_schema_plan(ds)
    col = next(
        c for c in plan.collections[0].table.columns if c.name == "identifikasjon"
    )
    assert col.id_inject_key == "lokalid"
    assert "lokalid" in col.strip_keys


def test_jsonb_field_with_server_managed_timestamp_iso_sets_write_inject():
    """server_managed timestamp_iso → ColumnPlan.write_inject populated."""
    ds = _make_dataset(
        fields=[
            ResolvedField(
                "identifikasjon",
                "jsonb",
                sub_fields=(
                    ResolvedField("lokalid", "text"),
                    ResolvedField("versjonid", "text"),
                ),
            )
        ],
        server_managed_paths={"identifikasjon.versjonid": "timestamp_iso"},
    )
    plan = build_schema_plan(ds)
    col = next(
        c for c in plan.collections[0].table.columns if c.name == "identifikasjon"
    )
    assert ("versjonid", "now()::text") in col.write_inject
    assert "versjonid" in col.strip_keys


def test_jsonb_field_both_server_managed_tokens():
    """Both outward_identifier and timestamp_iso in server_managed → all injection metadata set."""
    ds = _make_dataset(
        fields=[
            ResolvedField(
                "identifikasjon",
                "jsonb",
                sub_fields=(
                    ResolvedField("lokalid", "text"),
                    ResolvedField("versjonid", "text"),
                ),
            )
        ],
        server_managed_paths={
            "identifikasjon.lokalid": "outward_identifier",
            "identifikasjon.versjonid": "timestamp_iso",
        },
    )
    plan = build_schema_plan(ds)
    col = next(
        c for c in plan.collections[0].table.columns if c.name == "identifikasjon"
    )
    assert col.id_inject_key == "lokalid"
    assert ("versjonid", "now()::text") in col.write_inject
    assert set(col.strip_keys) == {"lokalid", "versjonid"}


def test_standalone_outward_identifier_sets_id_inject_key_and_strip():
    """outward_identifier_path alone (no server_managed entry) must populate
    id_inject_key and strip_keys on the matching JSONB ColumnPlan.
    """
    ds = _make_dataset(
        fields=[
            ResolvedField(
                "identifikasjon",
                "jsonb",
                sub_fields=(
                    ResolvedField("lokalid", "text"),
                    ResolvedField("versjonid", "text"),
                ),
            )
        ],
        outward_identifier_path="identifikasjon.lokalid",
        server_managed_paths={"identifikasjon.versjonid": "timestamp_iso"},
    )
    plan = build_schema_plan(ds)
    col = next(
        c for c in plan.collections[0].table.columns if c.name == "identifikasjon"
    )
    assert col.id_inject_key == "lokalid"
    assert "lokalid" in col.strip_keys
    # The server_managed versjonid injection must still be present.
    assert ("versjonid", "now()::text") in col.write_inject
    assert "versjonid" in col.strip_keys


def test_non_jsonb_field_has_no_injection_metadata():
    """A plain scalar field must not accidentally pick up injection metadata."""
    ds = _make_dataset(
        fields=[ResolvedField("medium", "text")],
    )
    plan = build_schema_plan(ds)
    col = next(c for c in plan.collections[0].table.columns if c.name == "medium")
    assert col.strip_keys == ()
    assert col.id_inject_key is None
    assert col.write_inject == ()


# --------------------------------------------------------------------------
# IndexPlan generation (Commit 3)
# --------------------------------------------------------------------------


def test_indexable_sub_field_of_jsonb_produces_functional_index():
    """indexable:True on a JSONB sub-field → functional IndexPlan in TablePlan.indexes."""
    ds = _make_dataset(
        fields=[
            ResolvedField(
                "identifikasjon",
                "jsonb",
                sub_fields=(ResolvedField("lokalid", "text", indexable=True),),
            )
        ],
    )
    plan = build_schema_plan(ds)
    exprs = [idx.expression for idx in plan.collections[0].table.indexes]
    assert any("identifikasjon" in e and "lokalid" in e for e in exprs)


def test_indexable_scalar_field_produces_regular_index():
    """indexable:True on a scalar field → IndexPlan with the column name."""
    ds = _make_dataset(
        fields=[ResolvedField("medium", "text", indexable=True)],
    )
    plan = build_schema_plan(ds)
    exprs = [idx.expression for idx in plan.collections[0].table.indexes]
    assert any("medium" in e for e in exprs)


def test_non_indexable_scalar_field_produces_no_extra_index():
    """indexable:False (default) on a scalar field → no IndexPlan."""
    ds = _make_dataset(
        fields=[ResolvedField("medium", "text", indexable=False)],
    )
    plan = build_schema_plan(ds)
    exprs = [idx.expression for idx in plan.collections[0].table.indexes]
    assert not any("medium" in e for e in exprs)


def test_parent_level_indexable_on_jsonb_does_not_produce_index():
    """indexable on the parent object field itself is ignored; only sub-fields matter."""
    ds = _make_dataset(
        fields=[
            ResolvedField(
                "identifikasjon",
                "jsonb",
                indexable=True,  # parent marked, not the sub-field
                sub_fields=(ResolvedField("lokalid", "text", indexable=False),),
            )
        ],
    )
    plan = build_schema_plan(ds)
    exprs = [idx.expression for idx in plan.collections[0].table.indexes]
    assert not any("identifikasjon" in e for e in exprs)


# --------------------------------------------------------------------------
# codelist_values flow to ColumnPlan (Commit 5 prerequisite)
# --------------------------------------------------------------------------


def test_codelist_values_flow_from_resolved_field_to_column_plan():
    """Suspect: codelist_values on ResolvedField must reach ColumnPlan unchanged
    so the SQL generator can emit validation without re-reading descriptions."""
    ds = _make_dataset(
        fields=[ResolvedField("medium", "text", codelist_values=("ASFALT", "GRUS"))],
    )
    plan = build_schema_plan(ds)
    col = next(c for c in plan.collections[0].table.columns if c.name == "medium")
    assert col.codelist_values == ("ASFALT", "GRUS")


# --------------------------------------------------------------------------
# Scalar server_managed → server_write_expr on ColumnPlan (Commit 8a)
# --------------------------------------------------------------------------


def test_scalar_server_managed_timestamp_iso_sets_server_write_expr():
    """Pre-code suspect: a single-segment server_managed path with token
    timestamp_iso must produce server_write_expr='now()' on the ColumnPlan,
    indicating the column is server-computed and must not use client input."""
    ds = _make_dataset(
        fields=[ResolvedField("oppdateringsdato", "timestamp", required=True)],
        server_managed_paths={"oppdateringsdato": "timestamp_iso"},
    )
    plan = build_schema_plan(ds)
    col = next(
        c for c in plan.collections[0].table.columns if c.name == "oppdateringsdato"
    )
    assert col.server_write_expr == "now()"


def test_scalar_without_server_managed_has_no_server_write_expr():
    """Suspect: a plain scalar field not in server_managed must have
    server_write_expr=None so it stays in the writable set."""
    ds = _make_dataset(
        fields=[ResolvedField("datafangstdato", "date", required=True)],
    )
    plan = build_schema_plan(ds)
    col = next(
        c for c in plan.collections[0].table.columns if c.name == "datafangstdato"
    )
    assert col.server_write_expr is None


# --------------------------------------------------------------------------
# postgis: extra index DDL from IndexPlan (Commit 4)
# --------------------------------------------------------------------------


def _stmts_for_indexable_dataset() -> list[str]:
    ds = _make_dataset(
        fields=[
            ResolvedField("medium", "text", indexable=True),
            ResolvedField(
                "identifikasjon",
                "jsonb",
                sub_fields=(ResolvedField("lokalid", "text", indexable=True),),
            ),
        ],
    )
    return postgis.table_statements(build_schema_plan(ds))


def test_indexable_scalar_produces_index_statement_in_ddl():
    stmts = _stmts_for_indexable_dataset()
    assert any('"medium"' in s and "create" in s and "index" in s for s in stmts)


def test_indexable_jsonb_sub_field_produces_functional_index_statement():
    stmts = _stmts_for_indexable_dataset()
    assert any("identifikasjon" in s and "lokalid" in s and "index" in s for s in stmts)


def test_extra_index_statement_uses_if_not_exists():
    stmts = _stmts_for_indexable_dataset()
    extra = [s for s in stmts if "medium" in s and "index" in s]
    assert extra, "expected at least one index statement for 'medium'"
    assert all("if not exists" in s for s in extra)


def test_extra_index_statement_uses_qualified_table_name():
    stmts = _stmts_for_indexable_dataset()
    extra = [s for s in stmts if "medium" in s and "index" in s]
    assert all("x.c" in s for s in extra)  # dataset 'x', collection 'c'


def test_no_extra_index_statements_when_indexes_empty():
    ds = _make_dataset(fields=[ResolvedField("medium", "text")])
    stmts = postgis.table_statements(build_schema_plan(ds))
    # Only the always-present geometry index should appear; no extra ones.
    extra = [s for s in stmts if "medium" in s and "index" in s]
    assert not extra
